[package]
name = "nustool-cli"
version = "0.1.0"
authors = ["Lukas Krickl <lukas@krickl.dev>"]
description = ""
license = "MIT"
homepage = "https://github.com/unlink2/nustool"
edition = "2021"

[[bin]]
name = "nustool"
path = "src/main.rs"

[dependencies]
nustool = {path = "../lib"}
